package io.lorde.meh;

public enum TokenType {
    // operators
    PLUS, MINUS, SLASH, STAR, EQUALS, ARROW, COLON, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_SQUARE_BRACKET,
    CLOSE_SQUARE_BRACKET, EQUAL_TO, LESS_THAN, GREATER_THAN, LESS_OR_EQUAL_TO, GREATER_OR_EQUAL_TO, NOT_EQUAL_TO,
    AMP, PIPE, SHIFT_LEFT, SHIFT_RIGHT, COMMA, PERCENT,

    // literals:w
    IDENTIFIER, NUMBER_INTEGER, NUMBER_FLOAT, TRUE, FALSE, STRING_LITERAL,

    // types
    STRING, BYTE, FLOAT, DOUBLE, FILE, INTEGER, VOID, BOOL, ANY,

    // keywords
    LET, BACK_SLASH, RETURN, IF, ELSE, AND, OR, NOT, AS, IS,

    // others
    SPACE, NEW_LINE, EOF
}
